name: TermGet
description: TermGet, Your Terminal's Software Center
remote_theme: b2a3e8/jekyll-theme-console

header_pages:
  - README.md
  - quickstart.md

style: dark # dark (default) or light
footer: '&copy 2019 The TermGet Team. All rights reserved.'
